# Generated by Django 6.1 on 2026-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('author_name', models.CharField(max_length=150, verbose_name='Auteur / Maker')),
                ('category', models.CharField(default='Impression 3D & IoT', max_length=100, verbose_name='Domaine / Spécialité')),
                ('description', models.TextField(verbose_name="Description complète et tutoriel d'assemblage")),
                ('license', models.CharField(choices=[('CC-BY-SA', 'Creative Commons BY-SA 4.0'), ('CC-BY-NC', 'Creative Commons Non-Commercial'), ('MIT', 'Licence MIT (Open Source)'), ('CERN-OHL', 'CERN Open Hardware Licence')], default='CC-BY-SA', max_length=30, verbose_name='Licence Open Source')),
                ('is_public', models.BooleanField(default=True, verbose_name='Projet Public sur le Hub')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet Maker',
                'verbose_name_plural': 'Galerie de Projets Makers',
                'ordering': ['-created_at'],
            },
        ),
    ]
