# Generated by Django 6.1 on 2026-08-26 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du canal / Sujet')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('channel_type', models.CharField(choices=[('PUBLIC', 'Canal Public (Tout le FabLab)'), ('FABMANAGER', 'Canal Équipe FabManager'), ('HELP', 'Entraide & Support Makers'), ('DIRECT', 'Message Direct / Privé')], default='PUBLIC', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description / Thème')),
                ('icon', models.CharField(default='💬', max_length=10, verbose_name='Emoji / Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de Discussion',
                'verbose_name_plural': 'Canaux de Discussion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du Tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#3b82f6', max_length=30, verbose_name='Couleur Badge CSS')),
            ],
            options={
                'verbose_name': 'Tag de Message',
                'verbose_name_plural': 'Tags de Messages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=150, verbose_name='Auteur')),
                ('sender_role', models.CharField(default='Maker', max_length=50, verbose_name='Rôle Auteur')),
                ('content', models.TextField(verbose_name='Contenu du message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='Pièce jointe (Fichier / Photo)')),
                ('is_announcement', models.BooleanField(default=False, verbose_name='Annonce officielle')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.channel')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='messages', to='core.messagetag')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
