# Generated by Django 6.1 on 2026-08-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Privé sur invitation uniquement'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('PUBLIC', 'Canal Public (Tout le FabLab)'), ('FABMANAGER', 'Canal Équipe FabManager'), ('GROUP', 'Groupe / Projet Sur Invitation'), ('HELP', 'Entraide & Support Makers'), ('DIRECT', 'Message Direct / Privé')], default='PUBLIC', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.CharField(default='', max_length=10, verbose_name='Icône'),
        ),
    ]
