# Generated by Django 6.1 on 2026-08-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='cpu', max_length=50, verbose_name='Icône SVG / CSS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Catégorie d'Équipement",
                'verbose_name_plural': "Catégories d'Équipements",
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la machine')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Marque / Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de Série')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Opérationnel / Disponible'), ('RESERVED', 'En Utilisation / Réservé'), ('MAINTENANCE', 'En Maintenance'), ('OFFLINE', 'Hors Service')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tarif Horaire (€)')),
                ('location_zone', models.CharField(default='Atelier Principal', max_length=100, verbose_name='Zone dans le FabLab')),
                ('power_watts', models.IntegerField(default=500, verbose_name='Puissance (Watts)')),
                ('safety_instructions', models.TextField(blank=True, verbose_name='Consignes de Sécurité / EPI requis')),
                ('requires_certification', models.BooleanField(default=True, verbose_name='Nécessite une Habilitation/Formation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Photo de la machine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Équipement / Machine',
                'verbose_name_plural': 'Équipements & Machines',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by_username', models.CharField(default='Membre', max_length=150, verbose_name='Rapporté par')),
                ('issue_title', models.CharField(max_length=200, verbose_name='Titre du Problème')),
                ('description', models.TextField(verbose_name='Description détaillée de la panne')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgent / Machine Bloquée')], default='MEDIUM', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('OPEN', 'Signalé'), ('IN_PROGRESS', "En cours d'intervention"), ('RESOLVED', 'Résolu / Réparé')], default='OPEN', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Ticket de Maintenance',
                'verbose_name_plural': 'Tickets de Maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
