# Generated by Django 6.1 on 2026-08-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_maintenanceticket_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='equipment_docs/', verbose_name='Fichier Notice / Documentation (PDF)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='doc_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Web Manuel / Tutoriel (URL)'),
        ),
    ]
