# Generated by Django 6.1 on 2026-08-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'atelier")),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('instructor_name', models.CharField(max_length=150, verbose_name='Formateur / Animateur')),
                ('description', models.TextField(verbose_name='Description complète et programme')),
                ('start_date', models.DateTimeField(verbose_name='Date & Heure de Début')),
                ('end_date', models.DateTimeField(verbose_name='Date & Heure de Fin')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="Prix d'entrée (€)")),
                ('max_seats', models.IntegerField(default=10, verbose_name='Places maximales')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name="Image d'illustration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atelier & Formation',
                'verbose_name_plural': 'Ateliers & Formations',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=200, verbose_name='Nom Complet du Participant')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('payment_status', models.CharField(choices=[('FREE', 'Gratuit'), ('PENDING', 'En Attente'), ('PAID', 'Payé')], default='PAID', max_length=20, verbose_name='Statut du Paiement')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Inscription Atelier',
                'verbose_name_plural': 'Inscriptions Ateliers',
            },
        ),
    ]
