# Generated by Django 6.1 on 2026-08-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_instructor_workshopregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.CharField(choices=[('PRINT3D', 'Impression 3D'), ('LASER', 'Découpe Laser'), ('CNC', 'Usinage CNC'), ('ELECTRONICS', 'Électronique & IoT'), ('CAD', 'Modélisation & CAO'), ('GENERAL', 'Initiation & Sécurité')], default='GENERAL', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='Description complète et objectifs de la formation'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'atelier / formation"),
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du cours / chapitre')),
                ('description', models.TextField(blank=True, verbose_name='Contenu / Notes de cours')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien vidéo tutoriel (Tutoriel YouTube/Vimeo)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Cours / Chapitre',
                'verbose_name_plural': 'Cours / Chapitres',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document / ressource')),
                ('file', models.FileField(blank=True, null=True, upload_to='workshop_resources/', verbose_name='Fichier (PDF, ZIP, STL, etc.)')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Externe (optionnel)')),
                ('resource_type', models.CharField(choices=[('PDF', 'Document PDF'), ('DOC', 'Fichier Texte / Doc'), ('ARCHIVE', 'Fichier CAD / ZIP / STL / DXF'), ('LINK', 'Lien Web Utile')], default='PDF', max_length=20, verbose_name='Type de ressource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='workshops.courselesson')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_resources', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Ressource de cours',
                'verbose_name_plural': 'Ressources de cours',
            },
        ),
    ]
