# Generated by Django 6.1 on 2026-08-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'habilitation")),
                ('level', models.CharField(choices=[('NOVICE', 'Niveau 1 : Initiation / Assisté'), ('AUTONOMOUS', 'Niveau 2 : Autonome'), ('EXPERT', 'Niveau 3 : Expert / Formateur')], default='AUTONOMOUS', max_length=20, verbose_name="Niveau d'habilitation")),
                ('description', models.TextField(blank=True, verbose_name='Description des prérequis et compétences valides')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Certification / Habilitation',
                'verbose_name_plural': 'Certifications & Habilitations',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('user_full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('start_time', models.DateTimeField(verbose_name='Heure de Début')),
                ('end_time', models.DateTimeField(verbose_name='Heure de Fin')),
                ('status', models.CharField(choices=[('PENDING', 'En Attente de Validation'), ('APPROVED', 'Confirmée'), ('ACTIVE', "En cours d'utilisation"), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='APPROVED', max_length=20, verbose_name='Statut')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cout Total (€)')),
                ('project_description', models.TextField(blank=True, verbose_name='Description du travail à réaliser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('user_full_name', models.CharField(max_length=200, verbose_name='Nom complet du membre')),
                ('granted_at', models.DateField(auto_now_add=True, verbose_name='Accordée le')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Valide')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to='reservations.certification')),
            ],
            options={
                'verbose_name': 'Habilitation Membre',
                'verbose_name_plural': 'Habilitations Membres',
            },
        ),
    ]
