# Generated by Django 6.1 on 2026-08-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_user_usercertification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En Attente de Validation'), ('APPROVED', 'Confirmée'), ('ACTIVE', "En cours d'utilisation"), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
