# Generated by Django 6.1 on 2026-08-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('STUDENT', 'Pass Étudiant (15€/mois)'), ('MAKER_MONTHLY', 'Abonnement Maker (30€/mois)'), ('MAKER_ANNUAL', 'Abonnement Maker Annuel (300€/an)'), ('PRO', 'Abonnement Entreprise / Pro (100€/mois)')], default='MAKER_MONTHLY', max_length=30, verbose_name="Formule d'abonnement")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name="Date d'échéance")),
                ('price', models.DecimalField(decimal_places=2, default=30.0, max_digits=8, verbose_name='Montant (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement Membre',
                'verbose_name_plural': 'Abonnements Membres',
                'ordering': ['-created_at'],
            },
        ),
    ]
