# Generated by Django 6.1 on 2026-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Compte Approuvé / Validé par le Responsable'),
        ),
    ]
