# Generated by Django 6.1 on 2026-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dossier_document',
            field=models.FileField(blank=True, null=True, upload_to='user_dossiers/', verbose_name='Justificatif / Carte Étudiant / Document Dossier'),
        ),
    ]
