# Generated by Django 6.1 on 2026-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'article")),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Code SKU / Référence')),
                ('category', models.CharField(default='Impression 3D', max_length=100, verbose_name='Catégorie')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantité en stock')),
                ('unit', models.CharField(choices=[('KG', 'Kilogrammes'), ('SPOOL', 'Bobines 1kg'), ('SHEET', 'Plaques / Feuilles'), ('PIECE', 'Pièces unitaire'), ('METER', 'Mètres')], default='PIECE', max_length=20, verbose_name='Unité de mesure')),
                ('min_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name="Seuil d'alerte stock bas")),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Prix Unitaire Vente (€)')),
                ('location', models.CharField(default='Étagère A1', max_length=100, verbose_name='Emplacement dans la réserve')),
            ],
            options={
                'verbose_name': 'Article de Stock / Consommable',
                'verbose_name_plural': 'Inventaire & Consommables',
            },
        ),
    ]
