# Generated by Django 6.1 on 2026-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du FabLab')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (identifiant unique)')),
                ('domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sous-domaine ou nom de domaine')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fablab_logos/', verbose_name='Logo')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('city', models.CharField(default='Paris', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('plan', models.CharField(choices=[('COMMUNITY', 'Communautaire / Associatif'), ('UNIVERSITY', 'Universitaire / Éducation'), ('ENTERPRISE', 'Entreprise / Prototypage Pro')], default='COMMUNITY', max_length=50, verbose_name='Plan Tarifaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FabLab (Tenant)',
                'verbose_name_plural': 'FabLabs (Tenants)',
                'ordering': ['name'],
            },
        ),
    ]
