# Generated by Django 6.1 on 2026-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablabs', '0002_fablab_is_approved_fablab_justification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fablab',
            name='domain_verified',
            field=models.BooleanField(default=False, help_text="Tant que ce n'est pas coché, le domaine personnalisé est ignoré (les emails et liens utilisent le sous-domaine standard) pour éviter d'envoyer des liens morts si le DNS n'est pas réellement configuré.", verbose_name='Domaine vérifié par le SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='fablab',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de domaine personnalisé'),
        ),
    ]
